language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then pyrus install pecl/inotify && pyrus build pecl/inotify; fi"
    - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"extension=inotify.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
    - "composer install --no-progress"
